ElectronicStore/Models/Contact_Table.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Table
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

ElectronicStore/Controllers/ContactController.cs
using ElectronicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicStore.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        ElectronicStoreEntities obj = new ElectronicStoreEntities();

        public ActionResult AllContact()
        {
            return View(obj.Contact_Table.ToList());
        }

        // GET: Contact/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contact/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Delete/5
        public ActionResult Delete(Contact_Table IdToDel)
        {
            var d = obj.Contact_Table.Where(x => x.id == IdToDel.id).FirstOrDefault();
            obj.Contact_Table.Remove(d);
            obj.SaveChanges();
            return RedirectToAction("AllContact");
        }

        // POST: Contact/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ElectronicStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicStore.Models;
namespace ElectronicStore.Controllers
{
    public class HomeController : Controller
    {
        //Conn Instance Object of SQl Connection Class
        SqlConnection sqlCon;
        //String ConnectionString for Making the Connection between the Class and Database
        String conStr = "Data Source=DESKTOP-17CKR5L;Initial Catalog=ElectronicStore;Integrated Security=True";
        //Cmd Instance Object to Create the Relation between  the Commad to execute the sql Command 
        SqlCommand sqlcmd;
        // DReader is instance to read the data from the database and pass to the Class
        SqlDataReader DReader;


        public void QueryRecord(String query)
        {
            sqlCon = new SqlConnection(conStr);
            sqlCon.Open();
            sqlcmd = new SqlCommand(query, sqlCon);
            sqlcmd.ExecuteNonQuery();
            sqlCon.Close();
        }



        public ActionResult Index()
        {
            return View();
        }

        // this method is used to search the record from the data base and then pass the whole record to the query using where clause of the sql
        public DataTable srchRecord(String qry)
        {
            DataTable tbl = new DataTable();

            sqlCon = new SqlConnection(conStr);

            sqlCon.Open();
            sqlcmd = new SqlCommand(qry, sqlCon);

            DReader = sqlcmd.ExecuteReader();

            tbl.Load(DReader);

            sqlCon.Close();

            return tbl;
        }
        public ActionResult AdminLogin() {
            return View();
        }

        public ActionResult Pannel()
        {
            return View();
        }
        public ActionResult  wrong()
        {
            return View();
        }


        public ActionResult Admin(Admin adm){
            string qry = "select * from Admin_Table where User_Name='"+adm.User_Email+"' and User_Password='"+adm.User_Password+"'";
            DataTable tbl = new DataTable();
            tbl = srchRecord(qry);
            if (tbl.Rows.Count>0) {

                return View("pannel");
            }
            else {
                return View("wrong");
            }

        }

        public ActionResult feed() {
            return View();
        }
        public ActionResult passMsg(Conact msg) {

            String qry = "insert into Contact_Table(Name,Email,Message) values ('"+msg.User_Name+"','"+msg.User_Email+"','"+msg.User_Message+"')";
            QueryRecord(qry);
            return View("feed");

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ElectronicStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicStore.Models;
using System.IO;
using System.Net;
using System.Data.Entity;

namespace ElectronicStore.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        ElectronicStoreEntities obj = new ElectronicStoreEntities();

        [HttpGet]
        public ActionResult ProductList()
        {
            return View(obj.Product_Table.ToList());
        }

        [HttpGet]
        public ActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(HttpPostedFileBase file,Product_Table prod)
        {
            string filename = Path.GetFileName(file.FileName);
            string _filename = DateTime.Now.ToString("yymmssfff") + filename;
            string extension = Path.GetExtension(file.FileName);
            string path = Path.Combine(Server.MapPath("~/ProductImage/"), _filename);
            prod.Image = "~/ProductImage/" + _filename;
            if (extension.ToLower()==".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png") {

                if (file.ContentLength <= 1000000)
                {

                    obj.Product_Table.Add(prod);
                    if (obj.SaveChanges() > 0)
                    {
                        file.SaveAs(path);
                        ViewBag.msg = "Record added ";
                        ModelState.Clear();
                    }
                }
                else {
                    ViewBag.msg = "Sizeis In valid  ";
                }
            }
            return RedirectToAction("ProductList");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id==null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var img = obj.Product_Table.Find(id);
            Session["imgPath"] = img.Image;
            if (img==null) {
                return HttpNotFound();
            }
            return View(img);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFile file,Product_Table prod)
        {
            if (ModelState.IsValid) {

                if (file != null)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                    string extension = Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/ProductImage/"), _filename);
                    prod.Image = "~/ProductImage/" + _filename;
                    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                    {

                        
                        if (file.ContentLength <= 1000000)
                        {

                            obj.Entry(prod).State = EntityState.Modified;
                            string oldImgPath = Request.MapPath(Session["imgPath"].ToString());

                            if (obj.SaveChanges() > 0)
                            {
                                file.SaveAs(path);
                                if (System.IO.File.Exists(oldImgPath)) {
                                    System.IO.File.Delete(oldImgPath);
                                }
                                TempData["msg"] = "Record Updated ";

                            }
                        }
                        else
                        {
                            ViewBag.msg = "Sizeis In valid  ";
                        }
                    }


                }
                else {
                    prod.Image = Session["imgPath"].ToString();
                    obj.Entry(prod).State = EntityState.Modified;
                    if (obj.SaveChanges()>0) {
                        TempData["msg"] = "Data Updated ";
                        return RedirectToAction("ProductList");
                    }
                }
            }



            return View();



        }


        // GET: Customer/Delete/5
        [HttpGet]
        public ActionResult Delete(Product_Table IdToDelete)
        {
            var d = obj.Product_Table.Where(x => x.id == IdToDelete.id).FirstOrDefault();
            obj.Product_Table.Remove(d);
            obj.SaveChanges();
            return RedirectToAction("ProductList");

        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

ElectronicStore/Controllers/SalaryController.cs
using ElectronicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicStore.Controllers
{
    public class SalaryController : Controller
    {
        // GET: Salary
        ElectronicStoreEntities obj = new ElectronicStoreEntities();

        public ActionResult SalaryDetails()
        {
            return View(obj.Salary_Table.ToList());
        }

        // GET: Salary/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Salary/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Salary/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "id")] Salary_Table db)
        {
            if (!ModelState.IsValid)
                return View();
            obj.Salary_Table.Add(db);
            obj.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return RedirectToAction("SalaryDetails");

        }

        // GET: Salary/Edit/5
        public ActionResult Edit(int id)
        {
            var IdToEdit = (from m in obj.Salary_Table where m.id == id select m).First();
            return View(IdToEdit);
        }

        // POST: Salary/Edit/5
        [HttpPost]
        public ActionResult Edit(Salary_Table IdToEdit)
        {
            var orignalRecord = (from m in obj.Salary_Table where m.id == IdToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj.Entry(orignalRecord).CurrentValues.SetValues(IdToEdit);

            obj.SaveChanges();
            return RedirectToAction("SalaryDetails");


        }

        // GET: Salary/Delete/5
        public ActionResult Delete(Salary_Table IdToDel)
        {
            var d = obj.Salary_Table.Where(x => x.id == IdToDel.id).FirstOrDefault();
            obj.Salary_Table.Remove(d);
            obj.SaveChanges();
            return RedirectToAction("SalaryDetails");
        }

        // POST: Salary/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ElectronicStore/Controllers/StaffController.cs
using ElectronicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicStore.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff

        ElectronicStoreEntities obj = new ElectronicStoreEntities();

        public ActionResult StaffDetails()
        {
            return View(obj.Staff_Table.ToList());
        }

        // GET: Staff/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "id")] Staff_Table tb)
        {
            if (!ModelState.IsValid)
                return View();
            obj.Staff_Table.Add(tb);
            obj.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return RedirectToAction("StaffDetails");

        }

        // GET: Staff/Edit/5
        public ActionResult Edit(int id)
        {
            var IdToEdit = (from m in obj.Staff_Table where m.id == id select m).First();
            return View(IdToEdit);
        }

        // POST: Staff/Edit/5
        [HttpPost]
        public ActionResult Edit(Staff_Table IdToEdit)
        {
            var orignalRecord = (from m in obj.Staff_Table where m.id == IdToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj.Entry(orignalRecord).CurrentValues.SetValues(IdToEdit);

            obj.SaveChanges();
            return RedirectToAction("StaffDetails");


        }

        // GET: Staff/Delete/5
        public ActionResult Delete(Staff_Table IdToDel)
        {
            var d =obj.Staff_Table.Where(x => x.id == IdToDel.id).FirstOrDefault();
            obj.Staff_Table.Remove(d);
            obj.SaveChanges();
            return RedirectToAction("StaffDetails");

        }

        // POST: Staff/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ElectronicStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ElectronicStore/Views/Home/AdminLogin.cshtml
@{
    ViewBag.Title = "AdminLogin";
}

<br/>

<div class="container">
    <div class="row">
        <div class="col-md-6">

            <img src="~/img/e5.jpg" class="img-thumbnail"/>

        </div>
        <div class="col-md-6">
            <form method="post" action="admin">
               
                <div class="form-group-lg">
                    <label>Enter Email </label> <br />
                    <input type="Email" class="form-control" name="User_Email" />
                </div>

                <div class="form-group-lg">
                    <label>Enter Password </label> <br />
                    <input type="password" class="form-control" name="User_Password" />
                </div>

                <input type="submit" value="Sign In" class="btn btn-danger" />


            </form>

        </div>

    </div>

</div>

ElectronicStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<br/>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <img src="~/img/e4.jpg" class="img-thumbnail"/>
            <form method="post" action="passMsg">
                
                <div class="form-group-lg">
                    <label>Enter Name </label> <br />
                    <input type="text" class="form-control" name="User_Name"/>
                </div>

                <div class="form-group-lg">
                    <label>Enter Email </label> <br />
                    <input type="Email" class="form-control" name="User_Email" />
                </div>

                <div class="form-group-lg">
                    <label>Enter Message </label> <br />
                    <input type="text" class="form-control" name="User_Message" />
                </div>

                <input type="submit" value="Send Message" class="btn btn-danger" />

            </form>
        </div>


    </div>

</div>

ElectronicStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<br/>

<div class="container-fluid">
    
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/img/e1.jpg" alt="Los Angeles" class="img-thumbnail" style="width:100%;">
            </div>

            <div class="item">
                <img src="~/img/e2.jpg" alt="Chicago" class="img-thumbnail" style="width:100%;">
            </div>

            <div class="item">
                <img src="~/img/e3.jpg" alt="New york" class="img-thumbnail" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="font-weight:bold;color:white;">Electronic components</h1>
            <p style="text-align:justify;color:white;font-size:18px;">
                If you've ever looked down on a city from a skyscraper window, you'll have marveled at all the tiny little buildings beneath you and the streets linking them together in all sorts of intricate ways. Every building has a function and the streets, which allow people to travel from one part of a city to another or visit different buildings in turn, make all the buildings work together. The collection of buildings, the way they're arranged, and the many connections between them is what makes a vibrant city so much more than the sum of its individual parts.
                <br/>
                The circuits inside pieces of electronic equipment are a bit like cities too: they're packed with components (similar to buildings) that do different jobs and the components are linked together by cables or printed metal connections (similar to streets). Unlike in a city, where virtually every building is unique and even two supposedly identical homes or office blocks may be subtly different, electronic circuits are built up from a small number of standard components. But, just like LEGO®, you can put these components together in an infinite number of different places so they do an infinite number of different jobs.

            </p>


        </div>

    </div>
</div>

ElectronicStore/Views/Home/Pannel.cshtml
@{
    ViewBag.Title = "Pannel";
}


<div class="container"> 
     <div class="row">
         <div class="col-md-12">

             <h1 align="center"> Wel come to the Admin Pannel </h1>
             <hr />
             <h2> <a href="@Url.Action("ProductList","Product")">List of  Product </a></h2>
             <h2> <a href="@Url.Action("StaffDetails","Staff")">List of  Employee </a></h2>
             <h2> <a href="@Url.Action("SalaryDetails","Salary")">List of  Salary </a></h2>
             <h2> <a href="@Url.Action("AllContact","Contact")">List of  Contact </a></h2>

         </div>


     </div>

</div>

ElectronicStore/Views/Home/feed.cshtml
@{
    ViewBag.Title = "feed";
}



<h1>Thanks for the Contact we will reply you soon ! </h1>

<a href="@Url.Action("Index","Home")">Back to site </a>

ElectronicStore/Views/Home/wrong.cshtml
@{
    ViewBag.Title = "wrong";
}

<h1> Try to Login with correct User Name or Password </h1>

<hr/>

<a href="@Url.Action("AdminLogin","Home")" class="btn btn-warning">Click Here to Login Again </a>